Models/Cart.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
	public class Cart
	{
		public int Customer_ID { get; set; }
		public Customer Customer { get; set; }

		[Display(Name="Product")]
		public long ISBN { get; set; }
		public Book Book { get; set; }

		public int Volume { get; set; }


	}
}

Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.Data;
using Project.Models;

namespace Project.Controllers
{
    public class CustomersController : Controller
    {
        private readonly MvcBookContext _context;

        public CustomersController(MvcBookContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Email,TelephoneNumber")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Email,TelephoneNumber")] Customer customer)
        {
            if (id != customer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.ID == id);
        }
    }
}

Controllers/HomeController.cs
	using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Logging;
using Project.Data;
using Project.Models;

namespace Project.Controllers
{
	public class HomeController : Controller
	{
		private readonly MvcBookContext _context;
		private readonly ILogger<HomeController> _logger;


		public HomeController(MvcBookContext context, ILogger<HomeController> logger)
		{
			_context = context;
			_logger = logger;
		}

		public async Task<IActionResult> Index()
		{
			LoadAuthors();
			LoadGenres();
			var mvcBookContext = _context.Books.Include(model => model.Genre).Include(model => model.Stockpile);
			return View(await mvcBookContext.ToListAsync());
		}

		public IActionResult Filter(String SearchString, String[] selectedAuthors, String[] selectedGenres)
		{
			ViewData["CurrentFilter"] = SearchString;

			var WrittenBooks = (from model in _context.BookAuthors select model).Include(model => model.Book);

			List<String> Authors = new List<String>(selectedAuthors);
			List<String> Genres = new List<string>(selectedGenres);
			IQueryable<Written_By> item= _context.BookAuthors;
			

			if (!String.IsNullOrEmpty(SearchString) && Authors!=null && Genres==null)
			{
				item = WrittenBooks.Where(model => Authors.Contains(model.Author.Name) || model.Book.Title.Contains(SearchString));

			}else if (!String.IsNullOrEmpty(SearchString) && Authors==null && Genres==null)
			{
				item = WrittenBooks.Where(model => Authors.Contains(model.Author.Name));

			}else if(String.IsNullOrEmpty(SearchString) && Authors!=null && Genres==null)
			{
				item = WrittenBooks.Where(model => Authors.Contains(model.Author.Name));

			}else if(!String.IsNullOrEmpty(SearchString) && Authors!=null && Genres !=null)
			{
				item = WrittenBooks.Where(model => Authors.Contains(model.Author.Name) || model.Book.Title.Contains(SearchString) || Genres.Contains(model.Book.Genre.Name));
			
			}else if(String.IsNullOrEmpty(SearchString) && Authors!=null && Genres !=null)
			{
				item = WrittenBooks.Where(model => Authors.Contains(model.Author.Name) || Genres.Contains(model.Book.Genre.Name));
			
			}else if(!String.IsNullOrEmpty(SearchString) && Authors==null && Genres !=null)
			{
				item = WrittenBooks.Where(model => model.Book.Title.Contains(SearchString) || Genres.Contains(model.Book.Genre.Name));
			
			}else if(String.IsNullOrEmpty(SearchString) && Authors==null && Genres !=null)
			{
				item = WrittenBooks.Where(model => Genres.Contains(model.Book.Genre.Name));
			}


			LoadAuthors();
			LoadGenres();
			return View(nameof(Index),item.Select(model => model.Book));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddToCart(string BookId)
		{
			try
			{				
				if (ModelState.IsValid)
				{
					if(HttpContext.Session.Get("Email") == null){
						throw new ArgumentException("No logged user");
					}

					long ISBN = long.Parse(BookId);
					string Customer_Email=HttpContext.Session.GetString("Email");
					Task<Customer> Customer = _context.Customers.FirstOrDefaultAsync(model => model.Email == Customer_Email);
					var ExistingCart = _context.Carts.FirstOrDefaultAsync(model => model.Customer_ID == Customer.Result.ID && model.ISBN==ISBN);
					if(ExistingCart.Result != null)
					{
						ExistingCart.Result.Volume+=1;
					}else
					{
						Cart cart = new Cart { Customer_ID = Customer.Result.ID, ISBN = ISBN, Volume=1 };
						_context.Add(cart);
					}
					await _context.SaveChangesAsync();
				}
			}
			catch (DbUpdateException)
			{
				ModelState.AddModelError("", "Unable to add to Cart. " + "Try again, and if the problem persists " +
										"see your system administrator.");
			}

			// LoadAuthors();
			// var mvcBookContext = _context.Books.Include(b => b.Genre);
			// return View("Index",await mvcBookContext.ToListAsync());
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> BookInfo(long? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books.Include(i => i.BookAuthors).ThenInclude(i => i.Author)
			.Include(i => i.Genre).FirstOrDefaultAsync(m => m.ISBN == id);

			if (book == null)
			{
				return NotFound();
			}

			return View(book);
		}

		public async Task<IActionResult> Clear(){
			string Customer_Email = HttpContext.Session.GetString("Email");
			var Customer_ID = (from model in _context.Customers where model.Email == Customer_Email select model.ID)
				.ToListAsync().Result[0];
			var MvcBookContext = (from model in _context.Carts where model.Customer_ID== Customer_ID select model).ToArray();
			foreach(var cart in MvcBookContext){
				_context.Remove(cart);
			}
			await _context.SaveChangesAsync();

			return await Cart();
		}

		public async Task<IActionResult> Cart()
		{
			string Customer_Email = HttpContext.Session.GetString("Email");
			var Customer_ID = (from model in _context.Customers where model.Email == Customer_Email select model.ID)
				.ToListAsync().Result[0];
			var MvcBookContext = (from model in _context.Carts where model.Customer_ID== Customer_ID select model)
				.Include(model => model.Book).ToListAsync();
			var MvcBookContext1 = _context.Carts.Include(model => model.Book).AsNoTracking().ToListAsync();
			return View(await MvcBookContext);

		}

		public IActionResult About()
		{
			return View();
		}

		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Login(long? id)
		{
			if (ModelState.IsValid)
			{
				try
				{
					var user = await _context.Customers.FirstOrDefaultAsync(model => model.Email == Request.Form["Email"].ToString());
					var password = Request.Form["Password"].ToString();
			
					if(user != null)
					{

						HashAlgorithm hashAlg = new SHA256CryptoServiceProvider();
						// Convert the data to hash to an array of Bytes.
						byte[] bytValue = System.Text.Encoding.UTF8.GetBytes(password);
						// Compute the Hash. This returns an array of Bytes.
						byte[] bytHash = hashAlg.ComputeHash(bytValue);
						// Optionally, represent the hash value as a base64-encoded string, 
						// For example, if you need to display the value or transmit it over a network.
						string base64 = Convert.ToBase64String(bytHash);

						if (user.Password == base64)
						{
							HttpContext.Session.SetString("Email", user.Email);
							HttpContext.Session.SetString("Name", user.Name);

							LoadAuthors();
							LoadGenres();
							var mvcBookContext = _context.Books.Include(b => b.Genre).Include(model => model.Stockpile);
							return View("Index",await mvcBookContext.ToListAsync());
						}
					}
				}catch(Exception )
				{
					ModelState.AddModelError("", "Unable to Login. " + "Try again, and if the problem persists " +
						"see your system administrator.");
				}

			}
			return NotFound();
		}

		public async Task<IActionResult> Logout()
		{
			HttpContext.Session.Clear();
			var mvcBookContext = _context.Books.Include(b => b.Genre);
			return View(nameof(Index), await mvcBookContext.ToListAsync());
		}

		private void LoadAuthors()
		{
			var authors = _context.Authors.ToArray();
			ViewBag.Authors = authors;
		}

		private void LoadGenres()
		{
			var genres = _context.Genres.ToArray();
			ViewBag.Genres = genres;
		}



		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.Data;
using Project.Models;

namespace Project.Controllers
{
	public class OrdersController : Controller
	{
		private readonly MvcBookContext _context;

		public OrdersController(MvcBookContext context)
		{
			_context = context;
		}

		// GET: Orders
		public async Task<IActionResult> Index()
		{
			var mvcBookContext = _context.Orders.Include(o => o.Customer);
			return View(await mvcBookContext.ToListAsync());
		}

		// GET: Orders/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders
				.Include(o => o.Customer)
				.FirstOrDefaultAsync(m => m.ID == id);
			if (order == null)
			{
				return NotFound();
			}

			return View(order);
		}

		// GET: Orders/Create
		public IActionResult Create()
		{
			ViewData["CustomerId"] = new SelectList(_context.Customers, "ID", "ID");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(int? id, string Address)
		{
			if(id == null)
				return NotFound();

			var Customer = await _context.Customers.Include(model => model.Carts)
				.FirstOrDefaultAsync(model => model.Email == HttpContext.Session.GetString("Email"));
			if (Customer == null)
				return NotFound();

			var CustomerCart = Customer.Carts;
			if (CustomerCart == null)
				return NotFound();

			foreach(var cart in CustomerCart)
			{
				Order order = new Order
				{
					BookId = cart.ISBN,
					CustomerId = Customer.ID,
					Address = Address,
					Amount=cart.Volume,
					Date = Convert.ToDateTime(Request.Form["Date"].ToString())
				};

				var Stockpile = (from model in _context.Stockpiles where model.BookID==cart.ISBN select model).ToListAsync().Result[0];
				if(Stockpile.Volume < order.Amount){
					continue;
				}
				_context.Add(order);
				_context.Remove(cart);
				Stockpile.Volume-=order.Amount;
			}
			// _context.Remove(CustomerCart);
			await _context.SaveChangesAsync();

			return RedirectToAction("Index", "Home");
		}

		// GET: Orders/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders.FindAsync(id);
			if (order == null)
			{
				return NotFound();
			}
			ViewData["CustomerId"] = new SelectList(_context.Customers, "ID", "ID", order.CustomerId);
			return View(order);
		}

		// POST: Orders/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("ID,BookId,CustomerId,Address,Date")] Order order)
		{
			if (id != order.ID)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(order);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!OrderExists(order.ID))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["CustomerId"] = new SelectList(_context.Customers, "ID", "ID", order.CustomerId);
			return View(order);
		}

		// GET: Orders/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders
				.Include(o => o.Customer)
				.FirstOrDefaultAsync(m => m.ID == id);
			if (order == null)
			{
				return NotFound();
			}

			return View(order);
		}

		// POST: Orders/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var order = await _context.Orders.FindAsync(id);
			_context.Orders.Remove(order);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool OrderExists(int id)
		{
			return _context.Orders.Any(e => e.ID == id);
		}
	}
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>
<p>Created by Ivaylo Evtimov    FN: F98223</p>

Views/Home/BookInfo.cshtml
@model Project.Models.Book

@{
	ViewData["Title"] = "Book Info";
}

<section class="product-sec">
		<div class="container">
			<h1>
				@Html.DisplayFor(item => item.Title)
			</h1>
			<div class="row">
				<div class="col-md-6 slider-sec">

					@{
						var src=@Html.DisplayFor(item => item.Cover);
						var authors="";
						var genres="";
					}

					 <img src="~/images/Covers/@src" class="img-fluid">
				</div>
				<div class="col-md-6 slider-content">
					<p>@Html.DisplayFor(item => item.Info)</p>
					<ul>
						<li> 
							@foreach (var item in Model.BookAuthors)
							{
								authors += @item.Author.Name.ToString() + ", ";
							}
							<span>Автори: @authors</span>
						</li>
						<li>
							<span>Жанр: @Html.DisplayFor(item => item.Genre.Name)</span>
						</li>
						<li>
							<span class="name"> Цена: </span><span class="clm"></span>
							<span class="price">@Html.DisplayFor(item => item.Price)</span>
						</li>
					</ul>
					<div class="btn-sec">
						<button class="btn" asp-action="AddToCart">Добави към кошница</button>					</div>
				</div>
			</div>
		</div>
	</section>

Views/Home/Cart.cshtml
@model IEnumerable<Project.Models.Cart>

@{
	ViewData["Title"]="Shopping Cart";
	int totalCost=0;
}

<section class="cart_area section_padding">
	<div class="container">
		<div class="cart_inner">
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<th scope="col">@Html.DisplayNameFor(model => model.Book)</th>
							<th scope="col">@Html.DisplayNameFor(model => model.Book.Price)</th>
							<th scope="col">@Html.DisplayNameFor(model => model.Volume)</th>
							@* <th scope="col">Total</th> *@
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
                        {
							<tr>
								<td>
									<div class="media">
										<div class="d-flex">
											@{
                                                var src = @Html.DisplayFor(modelItem => item.Book.Cover);
											}
											<img src="~/images/Covers/@src" alt="" />
										</div>
										<div class="media-body">
										<p>@Html.DisplayFor(modelItem => item.Book.Title)</p>
										</div>
									</div>
								</td>
								<td>
									<h5>@Html.DisplayFor(modelItem => item.Book.Price) BGN</h5>
								</td>
								<td>
									<div class="product_count">
										<label class="input-number">x @Html.DisplayFor(modelItem => item.Volume)</label>
									</div>
								</td>
							</tr>
						}
					</tbody>
				</table>
				<div class="checkout_btn_inner float-right">
					<a class="btn_1" asp-action="Index">Продължи към пазаруването</a>
				

					<a data-fancybox data-src="#modal" href="javascript:;"  class="btn_1 checkout_btn_1" >Напред към Поръчка</a>
					<div style="display: none;" id="modal">
						<div class="order_box">
							<h2>Твойта Поръчка</h2>
							<ul class="list">
								<li>
									<a href="#">Книга
									<span>Общо</span>
									</a>
								</li>
								@foreach (Cart item in Model)
								{
									<li>
										<a asp-action="BookInfo" asp-route-id="@item.ISBN">
											@Html.DisplayFor(modelItem => item.Book.Title)
											<span class="middle">x @Html.DisplayFor(modelItem => item.Volume)</span>
											@{
												var cost=item.Book.Price*item.Volume;
												totalCost+=(int) cost;
												}
											
											<span class="last">@cost BGN</span>
										</a>
									</li>	
									}
							
							</ul>
							<ul class="list list_2">
								<li>
									<a href="#">Общо
									<span>@totalCost BGN</span>
									</a>
								</li>
							</ul>
							<p>
								Моля въведете коректен адрес и дата за доставка.
							</p>
						</div>
						@{
							int Customer_ID=0;
							if(Model.Count() != 0)
							{
								Customer_ID = Model.ElementAt(0).Customer_ID;
							}
						}
						<a class="btn_3" style="margin-top: 10px" asp-controller="Orders" asp-action="Create" asp-route-id=@Customer_ID >Въвеждане на Адрес и Дата</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>	

Views/Home/Index.cshtml
@model IEnumerable<Project.Models.Book>

@{
	ViewData["Title"] = "Home Page";
}

<main>
	<div class="popular-items section-padding30">
		<a data-fancybox data-src="#modal" href="javascript:;" class="btn_1 checkout_btn_1">Filter</a>
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-xl-7 col-lg-8 col-md-10">
					<div class="section-tittle mb-70 text-center">
						<h2>Налични книги</h2>
					</div>
				</div>
			</div>
			<div class="row">
				@foreach (var item in Model)
				{
					if(item.Stockpile.Volume<=0)
					{
						continue;
					}
					
					<div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
						<div class="single-popular-items mb-50 text-center">
							<div class="popular-img">
								@{
									var src = @Html.DisplayFor(modelItem => item.Cover);
								}
								<a asp-action="BookInfo" asp-route-id="@item.ISBN"> <img src="~/images/Covers/@src" alt=""></a>
								<div class="img-cap">
									<form asp-controller="Home" asp-action="AddToCart">
										<span>
											<button type="submit" name="BookId" value="@item.ISBN">Add to cart</button>
										</span>
									</form>
								</div>
								<div class="favorit-items">
									<span class="flaticon-heart"></span>
								</div>
							</div>
							<div class="popular-caption">
								<h3><a asp-action="BookInfo" asp-route-id="@item.ISBN">@Html.DisplayFor(modelItem => item.Title)</a></h3>
								<span>@Html.DisplayFor(modelItem => item.Price) BGN</span>
							</div>
						</div>
					</div>

				}

			</div>
		</div>


		<div style="display: none;" id="modal">
			<form asp-action="Filter" method="get">
								<div class="form-actions no-color">
										<p>
												Търсене: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
										</p>
										<label>Автори</label>
										<ul>
												@{
														foreach (var author in ViewBag.Authors)
														{
																@:<li>
																		<input type="checkbox" name="selectedAuthors" value="@author.Name" />
																		@author.Name
																@:</li>
														}
												}
										</ul>
										<br>
										<label>Жанрове</label>
										<ul>
											@{
												foreach(var genre in ViewBag.Genres)
												{
													@:<li>
														<input type="checkbox" name="selectedGenres" value="@genre.Name" />
														@genre.Name
													@:</li>
												}
											}
										</ul>
										<br>
										<input type="submit" value="Search" class="btn" />
								</div>
			</form>
			
		</div>

</main>

Views/Home/Login.cshtml
@model Project.Models.LoginViewData
@{
	ViewData["Title"] = "View";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="login_part section_padding ">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 col-md-6">
				<div class="login_part_text text-center">
					<div class="login_part_text_iner">
						<h2>Нов потербител?</h2>
						<p>Влезнетее в системата за да можете да поръчвате книги</p>
						<a asp-area="" asp-controller="Customers" asp-action="Create" class="btn_3">Създай потербител</a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="login_part_form">
					<div class="login_part_form_iner">
						<h3>Добре дошли! <br>
							Влезнете сега</h3>
						<form class="row contact_form" action="#" method="post" novalidate="novalidate">
							<div class="col-md-12 form-group p_star">
								<input asp-for="Email" type="text" class="form-control" id="email" name="email" value="" placeholder="Имейл">
							</div>
							<div class="col-md-12 form-group p_star">
								<input asp-for="Password" type="password" class="form-control" id="password" name="password" value="" placeholder="Парола">
							</div>
							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="btn_3">Влизане</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
		</section>